name: Test Run

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: setup-repo
        uses: actions/checkout@v2

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18 
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      - name: install-dependencies
        run : yarn

      - name: run-tests
        run: yarn run test
      

